apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: crossplane-system
stringData:
  creds: |
    [default]
    aws_access_key_id = AKIA24KHRWUJBRJKMQG7
    aws_secret_access_key = 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
