apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucketlkmcreation
  namespace: crossplane-system
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XmyVpc
  resources:
  - name: buckets3com
    base:
      apiVersion: s3.aws.upbound.io/v1beta1
      kind: Bucket
      metadata:
        name: mytestbukectlkm 
      spec:
        providerConfigRef:
          name: default
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
